export const PERFORMANCE_CONFIG = {
  cameraChangeThrottleMs: 300,
  enablePerformanceDebug: true,
  fetchDebounceMs: 300,
  maxPolygonPointsBeforeSimplify: 80,
  maxRealtimeEventsBuffered: 50,
  maxRenderedLocalTerritories: 120,
  maxRenderedOnlineTerritories: 250,
  polygonSimplificationTolerance: 0.00005,
  realtimeDebounceMs: 250,
  viewportBoundsEpsilon: 0.0001,
  viewportCenterEpsilon: 0.00005,
  viewportPaddingRatio: 0.2,
  viewportZoomEpsilon: 0.01,
} as const;
